require "tilt"
require "nesta-contentfocus-extensions/version"
require "nesta-contentfocus-extensions/app"
require "nesta-contentfocus-extensions/helpers"
require "nesta-contentfocus-extensions/menu"
require "nesta-contentfocus-extensions/overrides"
require "nesta-contentfocus-extensions/page"
require "nesta-contentfocus-extensions/path"
require "nesta-contentfocus-extensions/paths"
require "nesta-contentfocus-extensions/renderer"
require "nesta-contentfocus-extensions/routes"
require "nesta-contentfocus-extensions/theme"
Nesta::ContentFocus::Paths.add_sass_path(File.expand_path("../assets/stylesheets", File.dirname(__FILE__)))
Nesta::ContentFocus::Paths.add_public_path(File.expand_path("public", Nesta::Env.root))
Nesta::ContentFocus::Paths.add_view_path(File.expand_path("views", Nesta::Env.root))
